[build-system]
    build-backend = "setuptools.build_meta"
    requires      = ["setuptools>=61.0"]

[project]
    name = "lemonade-stand"
    version = "0.1.0"
    description = ""
    license = "MIT"
    readme = "README.md"
    requires-python = ">=3.13"
    authors = [{ name = "Kelvin", email = "kelvinmararia@icloud.com" }]
    dependencies = [
        "bcrypt>=5.0.0",
        "duckdb>=1.4.3",
        "faicons>=0.2.2",
        "great-tables>=0.20.0",
        "inquirerpy>=0.3.4",
        "llama-index>=0.14.10",
        "pdfplumber>=0.11.8",
        "plotly>=6.5.0",
        "polars>=1.36.1",
        "pyarrow>=22.0.0",
        "pymupdf4llm>=0.2.7",
        "shiny>=1.5.1",
        "shinywidgets>=0.7.0",
    ]

[project.optional-dependencies]
    formatters = ["pre-commit>=4.5.0", "ruff>=0.14.9"]
    tests      = ["pyright>=1.1.407", "pytest>=9.0.2"]

[project.scripts]
    budget = "lemonade_stand.app:initialize_app"

[tool.uv]
    link-mode = "copy"

[tool.ruff]
    # Same as Black.
    indent-width   = 4
    line-length    = 88
    target-version = "py311"

    # Exclude a variety of commonly ignored directories.
    exclude = [
        ".direnv",
        ".git",
        ".git-rewrite",
        ".pyenv",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".venv",
        ".vscode",
        "__pypackages__",
        "_build",
        "build",
        "dist",
        "site-packages",
        "venv",
    ]

[tool.ruff.lint]
    ignore = ["E501"]
    select = [
        "ARG",  # flakes-unused-arguments
        "B",    # flakes-bugbear
        "C4",   # flakes-comprehensions
        "D1",   # pydocstyle basics (i.e. no missing docstrings)
        "E",    # pycodestyle
        "F",    # Pyflakes
        "G",    # flakes-logging-format
        "I",    # isortI
        "N",    # peps-naming
        "NPY",  # Numpy deprecation catches
        "PD",   # pandas-vet
        "PT",   # Flakes-pytest-style
        "PTH",  # flakes-use-pathlib
        "SIM",  # flakes-Simplify
        "UP",   # pyupgrade
        "W",
        "I",
        "D210",
    ]

[tool.ruff.lint.isort]
    force-single-line = true

[tool.ruff.lint.per-file-ignores]
    "__init__.py" = ["F401"]

[tool.ruff.format]
    docstring-code-format      = false     # Enable auto-formatting of code examples in docstrings.
    docstring-code-line-length = "dynamic" # Set the line length limit used when formatting code snippets in docstrings.
    indent-style               = "space"   # Like Black, indent with spaces, rather than tabs.
    line-ending                = "lf"      # Like Black, automatically detect the appropriate line ending.
    quote-style                = "double"  # Like Black, use double quotes for strings.
    skip-magic-trailing-comma  = false     # Like Black, respect magic trailing commas.
