[project]
    name = "lemonade-stand"
    version = "0.1.0"
    description = ""
    license = "MIT"
    readme = "README.md"
    requires-python = ">=3.13"
    authors = [{ name = "Kelvin", email = "kelvinmararia@icloud.com" }]
    dependencies = [
        "countrystatecity-countries>=1.0.2",
        "llama-index>=0.14.21",
        "pdfplumber>=0.11.9",
        "polars[rt64, deltalake]>=1.40.1",
        "pyarrow>=22.0.0",
        "pymupdf4llm==0.2.8",
        "python-dateutil>=2.9.0.post0",
        "reflex>=0.9.3",
        "scikit-learn>=1.8.0",
    ]

[dependency-groups]
    formatters = ["pre-commit>=4.5.0", "ruff>=0.14.9"]
    dev        = ["ipykernel>=7.2.0", "pyright>=1.1.409", "pytest>=9.0.2"]

[build-system]
    requires      = ["uv_build>=0.11.12,<0.12"]
    build-backend = "uv_build"

[tool.uv.build-backend]
    module-name = "lemonade_stand"
    module-root = ""

[tool.coverage.report]
    exclude_also = [
        "def __repr__",
        "def __str__",
        "\\A(?s:.*# pragma: exclude file.*)\\Z",
    ]

[tool.ruff]
    # Same as Black.
    indent-width   = 4
    line-length    = 88
    target-version = "py311"

    # Exclude a variety of commonly ignored directories.
    exclude = [
        ".direnv",
        ".git",
        ".git-rewrite",
        ".pyenv",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".venv",
        ".vscode",
        ".web",
        "__pypackages__",
        "_build",
        "build",
        "dist",
        "site-packages",
        "venv",
    ]

[tool.ruff.lint]
    ignore = ["E501"]
    select = [
        "ARG",  # flakes-unused-arguments
        "B",    # flakes-bugbear
        "C4",   # flakes-comprehensions
        "D1",   # pydocstyle basics (i.e. no missing docstrings)
        "E",    # pycodestyle
        "F",    # Pyflakes
        "G",    # flakes-logging-format
        "I",    # isortI
        "N",    # peps-naming
        "NPY",  # Numpy deprecation catches
        "PD",   # pandas-vet
        "PT",   # Flakes-pytest-style
        "PTH",  # flakes-use-pathlib
        "SIM",  # flakes-Simplify
        "UP",   # pyupgrade
        "W",
        "I",
        "D210",
    ]

[tool.ruff.lint.isort]
    force-single-line = true

[tool.ruff.lint.per-file-ignores]
    "__init__.py" = ["F401"]

[tool.ruff.format]
    docstring-code-format      = false     # Enable auto-formatting of code examples in docstrings.
    docstring-code-line-length = "dynamic" # Set the line length limit used when formatting code snippets in docstrings.
    indent-style               = "space"   # Like Black, indent with spaces, rather than tabs.
    line-ending                = "lf"      # Like Black, automatically detect the appropriate line ending.
    quote-style                = "double"  # Like Black, use double quotes for strings.
    skip-magic-trailing-comma  = false     # Like Black, respect magic trailing commas.
