[project]
    name = "banana-stand"
    version = "0.1.0"
    description = ""
    license = "MIT"
    readme = "README.md"
    requires-python = ">=3.12"
    authors = [{ name = "Kelvin Mararia", email = "kevohnjuguna254@gmail.com" }]
    dependencies = [
        "dash>=3.2.0",
        "inquirerpy>=0.3.4",
        "llama-index>=0.13.1",
        "pdfplumber>=0.11.7",
        "polars>=1.32.2",
        "pyarrow>=21.0.0",
        "pymupdf4llm>=0.0.27",
    ]

[project.optional-dependencies]
    dependencies = []
    test = [
        "pyright>=1.1.403",
        "pytest>=8.4.1",
        "ruff>=0.12.8",
    ]

[build-system]
    build-backend = "setuptools.build_meta"
    requires      = ["setuptools>=61.0"]

[tool.setuptools.packages.find]
    exclude = ["tests*", "tmp*"]
    include = ["lemonade_stand*"]

[tool.ruff]
    # Same as Black.
    indent-width   = 4
    line-length    = 88
    target-version = "py311"

    # Exclude a variety of commonly ignored directories.
    exclude = [
        ".direnv",
        ".git",
        ".git-rewrite",
        ".pyenv",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".venv",
        ".vscode",
        "__pypackages__",
        "_build",
        "build",
        "dist",
        "site-packages",
        "venv",
    ]

[tool.ruff.lint]
    ignore = ["E501"]
    select = [
        "ARG",  # flakes-unused-arguments
        "B",    # flakes-bugbear
        "C4",   # flakes-comprehensions
        "D1",   # pydocstyle basics (i.e. no missing docstrings)
        "E",    # pycodestyle
        "F",    # Pyflakes
        "G",    # flakes-logging-format
        "I",    # isortI
        "N",    # peps-naming
        "NPY",  # Numpy deprecation catches
        "PD",   # pandas-vet
        "PT",   # Flakes-pytest-style
        "PTH",  # flakes-use-pathlib
        "SIM",  # flakes-Simplify
        "UP",   # pyupgrade
        "W",
        "I",
        "D210",
    ]

[tool.ruff.lint.isort]
    force-single-line = true

[tool.ruff.lint.per-file-ignores]
    "__init__.py" = ["F401"]

[tool.ruff.format]
    docstring-code-format      = false     # Enable auto-formatting of code examples in docstrings.
    docstring-code-line-length = "dynamic" # Set the line length limit used when formatting code snippets in docstrings.
    indent-style               = "space"   # Like Black, indent with spaces, rather than tabs.
    line-ending                = "lf"      # Like Black, automatically detect the appropriate line ending.
    quote-style                = "double"  # Like Black, use double quotes for strings.
    skip-magic-trailing-comma  = false     # Like Black, respect magic trailing commas.
