include = ["**/*.toml"]
exclude = [
  "**/tmp/**",
]

[formatting]

[[rule]]

[rule.formatting]
include = ["taplo.toml"]
keys = ["exclude"]

array_auto_collapse = false

[[rule]]
include = ["pyproject.toml"]

[rule.formatting]
indent_string = '    '
indent_entries = true
align_entries = true
align_comments = true
allowed_blank_lines = 2
reorder_keys = true
