include = ["**/*.toml"]
exclude = []

[formatting]
    align_comments      = true
    align_entries       = true
    allowed_blank_lines = 2
    indent_entries      = true
    indent_string       = '    '
    reorder_keys        = false

[[rule]]
    include = ["taplo.toml"]
    keys    = ["formatting"]

[rule.formatting]
    array_auto_collapse = false
    reorder_keys        = true
