---
name: Run pre-commit

on:
    pull_request:
    push:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
            - name: Set up uv
              uses: astral-sh/setup-uv@v7
            - name: Set up python environment
              run: |
                  uv python install
                  uv sync --frozen
            - name: Run hooks
              run: uv run prek run --all-files
